#!/usr/bin/env python

import sys
import os

os.system("firefox http://gen.lib.rus.ec/search.php?req={}&lg_topic=libgen&open=0&view=simple&res=100&phrase=1&column=def".format('+'.join(sys.argv[1:])))
